[env]
DEFMT_LOG = "info"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = ["probe-rs", "run", "--chip", "STM32L476RG", "--connect-under-reset"]
linker = "flip-link"
rustflags = [
  "-C", "linker=rust-lld",   # 👈 AJOUT IMPORTANT
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x"
]

[build]
target = "thumbv7em-none-eabihf"

[alias]
rb = "run --bin"
rrb = "run --release --bin"